version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    # Allow up to 2 open pull requests for pip dependencies
    open-pull-requests-limit: 2
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    # Allow up to 2 open pull requests for pip dependencies
    open-pull-requests-limit: 2
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly
    # Allow up to 2 open pull requests for pip dependencies
    open-pull-requests-limit: 2
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    # Allow up to 2 open pull requests for pip dependencies
    open-pull-requests-limit: 2
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
