comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: TRUE # set to true
coverage:
  status:
    project:
      default:
        target: "100"
    patch:
      default:
        target: "100"
