version: 1
formatters:
  simple:
    format: "%(levelname)s - %(message)s"
  extended:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: extended
    filename: logs/gh-deployments.log
root:
  level: DEBUG
  handlers: [console, file]
