name: Benchmark
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  benchmark:
    name: Check performance regression.
    runs-on: ubuntu-latest
    permissions:
      # deployments permission to deploy GitHub pages website
      deployments: write
      # contents permission to update benchmark contents in gh-pages branch
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          disable-sudo: true
          egress-policy: block
          disable-telemetry: false
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            api.github.com:443

      - name: Checkout main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          clean: true

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.14"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install UV
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt uv
          uv --version

      - name: Install Nox
        run: |
          uvx pipx install --pip-args=--constraint=.github/workflows/constraints.txt nox
          nox --version

      - name: Run benchmark with nox
        env:
          UV_PREVIEW: 1
        run: nox -s benchmark

      - name: Store benchmark result in github.io
        uses: benchmark-action/github-action-benchmark@a60cea5bc7b49e15c1f58f411161f99e0df48372 # v1.22.0
        with:
          name: Pytest-Benchmark Benchmark
          tool: "pytest"
          output-file-path: benchmark-output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: "130%"
          comment-on-alert: true
          fail-on-alert: true
